FROM node:10.12.0-slim
LABEL MAINTAINER="Felipe Santos - @felps03 | Bruna Santos - @brunass"
ENV PORT=3333
ENV NODE_ENV=dev

COPY . /src
WORKDIR /src

RUN npm config set strict-ssl false && npm ci 
EXPOSE $PORT
CMD npm start